/*
 * Copyright 2022 Google LLC
 *
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#ifndef skgpu_graphite_DawnUtils_DEFINED
#define skgpu_graphite_DawnUtils_DEFINED

#include "include/core/SkImageInfo.h"
#include "include/ports/SkCFObject.h"
#include "src/gpu/graphite/ResourceTypes.h"
#include "src/sksl/ir/SkSLProgram.h"

#include "webgpu/webgpu_cpp.h"

namespace skgpu {
class ShaderErrorHandler;
}

namespace SkSL {
    class Compiler;
}

namespace skgpu::graphite {
class DawnSharedContext;

bool DawnFormatIsDepthOrStencil(wgpu::TextureFormat);
bool DawnFormatIsDepth(wgpu::TextureFormat);
bool DawnFormatIsStencil(wgpu::TextureFormat);

wgpu::TextureFormat DawnDepthStencilFlagsToFormat(SkEnumBitMask<DepthStencilFlags>);

/**
 * Produces SPIRV code generated by SkSLC
 */
bool SkSLToSPIRV(SkSL::Compiler*,
                 const std::string& sksl,
                 SkSL::ProgramKind kind,
                 const SkSL::ProgramSettings& settings,
                 std::string* spirv,
                 SkSL::Program::Inputs* outInputs,
                 ShaderErrorHandler* errorHandler);

/**
 * Produces WGSL code generated by SkSLC
 */
bool SkSLToWGSL(SkSL::Compiler*,
                const std::string& wgsl,
                SkSL::ProgramKind kind,
                const SkSL::ProgramSettings& settings,
                std::string* spirv,
                SkSL::Program::Inputs* outInputs,
                ShaderErrorHandler* errorHandler);

wgpu::ShaderModule DawnCompileSPIRVShaderModule(const DawnSharedContext* sharedContext,
                                                const std::string& spirv,
                                                ShaderErrorHandler* errorHandler);

wgpu::ShaderModule DawnCompileWGSLShaderModule(const DawnSharedContext* sharedContext,
                                               const std::string& wgsl,
                                               ShaderErrorHandler* errorHandler);

} // namespace skgpu::graphite

#endif // skgpu_graphite_DawnUtils_DEFINED
